### ISSUE TITLE
Expected output for testInsertKeyChain()

### ISSUE THREAD

**Issue by ConstBur** [Comp251CodeTests/Assignment1Tester#2]
Can someone confirm if the following is the expected output of testInsertKeyChain()? If it is, let's add this to the tester.

```
Table before insertion: 
[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]

Table after insertion using chain: 
[[20], [19], [], [18], [17], [], [16], [], [15], [14], [], [13], [12], [32], [11, 31], [], [10, 30], [9, 29], [], [8, 28], [7, 27], [], [6, 26], [], [5, 25], [4, 24], [], [3, 23], [2, 22], [], [1, 21], []
```

**Comment by ConstBur** [comment]
Just realized there is another branch: https://github.com/Comp251CodeTests/Assignment1Tester/tree/CompareAgainstExpected The tester there has a different (reversed) output for ArrayLists with multiple numbers.

**Comment by PierreMasselot1** [comment]
Hey, yeah I didn't merge it yet because I wanted someone else to confirm that these were the correct results. For the fact that the output is reversed in your case, I believe that you may have made an error since when chaining you are supposed to add at the head of the list. Can you just confirm that in the other tests it matches what you are getting? because if yes I will merge it to the main branch.

**Comment by PierreMasselot1** [comment]
Like in the case of the [11,31] you first add the 11 and then the 31 so the 31 should be at the head like so: [31,11]

**Comment by ConstBur** [comment]
Thanks for the quick reply @PierreMasselot1 ! I forgot about the inserting at the head part, so now the output matches :smile: I haven't done other methods yet, but when I will I'll make another comment (ideally should be by the end of the day).

**Comment by PierreMasselot1** [comment]
Yeah, just to let you know you can also insert the element at the end of the list so we are fixing the tester to accept both. Sorry for the extra time spend changing it when it was not really necessary.

**Comment by YazdanZ** [comment]
We added this feature in PR https://github.com/Comp251CodeTests/Assignment1Tester/pull/4
